# Generated by Django 3.1 on 2022-03-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefacts',
            old_name='empire_holding',
            new_name='empire_holding_id',
        ),
    ]
