# Generated by Django 3.1 on 2022-03-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220321_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefacts',
            old_name='empire_holding_id',
            new_name='empire_holding',
        ),
    ]
