# Generated by Django 3.1 on 2022-03-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testimonials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
