# Generated by Django 3.1 on 2022-03-27 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='crystals',
            field=models.BigIntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='ectrolium',
            field=models.BigIntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='energy',
            field=models.BigIntegerField(default=120000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='minerals',
            field=models.BigIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
