# Generated by Django 3.1 on 2022-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220327_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_buildings',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_cities',
            field=models.IntegerField(default=0),
        ),
    ]
