# Generated by Django 3.1 on 2022-07-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220630_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
