# Generated by Django 3.1 on 2022-07-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_halloffame_artefacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundstatus',
            name='artetimer',
            field=models.IntegerField(default=1440),
        ),
    ]
