# Generated by Django 3.1 on 2022-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_roundstatus_artetimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefactimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artetimer', models.IntegerField(default=1440)),
            ],
        ),
        migrations.RemoveField(
            model_name='roundstatus',
            name='artetimer',
        ),
    ]
