# Generated by Django 3.1 on 2022-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220702_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='tag',
            field=models.CharField(blank=True, default='Player', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='color_settings',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('O', 'Orange'), ('Y', 'Yellow'), ('I', 'Indigo'), ('V', 'Violet'), ('W', 'White'), ('P', 'Pink')], default='G', max_length=1),
        ),
    ]
