# Generated by Django 3.1 on 2022-07-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220717_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='post_attack_order',
            field=models.IntegerField(choices=[(1, 'Station On Planet'), (2, 'Wait In System'), (5, 'Recall To Main')], default=2),
        ),
    ]
