# Generated by Django 3.1 on 2022-08-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220721_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='popper',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='system',
            name='p0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='p3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='p4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='p5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='p6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='p7',
            field=models.IntegerField(default=0),
        ),
    ]
